# Generated by Django 4.2.6 on 2023-10-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "code",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("credits", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
